### ISSUE TITLE
Deformed header issue

### ISSUE THREAD

**Issue by mratkovic** [isovic/aligneval#1]
Problem evaluating read alignments (except generated Illumina reads). Float division by zero occurred due marking all lines in .sam file as deformed. 
reads.sam file is empty for all generated reads (except Illumina).

![screenshot - 23 03 2015 - 14 52 16](https://cloud.githubusercontent.com/assets/9074691/6784258/fd304dda-d17e-11e4-87b3-4251c82e00d9.png)

**Comment by mratkovic** [comment]
reads.sam was empty due to an error on  .maf to .sam conversion during read generating.
Setup downloads last-534, but during maf conversion script is called from last-460 directory.

As quick fix, I simply modified line in generate_data.py so the maf-convert script could be executed.

**Comment by isovic** [comment]
Fixed!
