### ISSUE TITLE
List index out of range error - run-simulated.py

### ISSUE THREAD

**Issue by mratkovic** [isovic/aligneval#2]
Error occurs on line 66 in run-simulated.py when 'machine_names[machine_num]' is accessed.

Reason for this is wrong placement of 'machine_num += 1;' (run-simulated.py: line 81).
It should have one level of indentation less because it should be incremented after corresponding dataset is simulated (outer for loop).

**Comment by isovic** [comment]
Good catch, thanks! Fixed!
